### ISSUE TITLE
Https not working

### ISSUE THREAD

**Issue by MarcelCoding** [jellyfin/jellyfin-android#345]
**Describe the bug**
I can't use https to connect to my jellyfin server.

**Setup**
I have my jellyfin instance running in a docker container:
```yaml
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    user: 1000:1000
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadBalancer.server.port=8096"
      - "traefik.http.routers.r_jellyfin.rule=PathPrefix(`/jellyfin/`) || Path(`/jellyfin`)"
      - "traefik.http.routers.r_jellyfin.entryPoints=websecure"
      - "traefik.http.routers.r_jellyfin.middlewares=mv_jellyfin-redirect@docker,mv_jellyfin-replace-path@docker"
      - "traefik.http.middlewares.mv_jellyfin-redirect.redirectregex.regex=^(.*/jellyfin)/?(web)?$$"
      - "traefik.http.middlewares.mv_jellyfin-redirect.redirectregex.replacement=$${1}/web/"
      - "traefik.http.middlewares.mv_jellyfin-replace-path.replacepathregex.regex=^(.*/jellyfin/web/)$$"
      - "traefik.http.middlewares.mv_jellyfin-replace-path.replacepathregex.replacement=$$1/index.html"
    networks:
      - proxy
```

In front of the jellyfin instance is a traefik wich does https. I have a local ca for my home network, this ca is in my browser and on my mobile phone imported. (screenshot -> browser on my phone)

I've tested the setup without a traefik and the port 8096 on the container opened directly and it worked.

**To Reproduce**
1. Create a certificate and import it in the required devices
1. Setup the docker stack
2. Test it on a browser
3. Test it in the app -> not working -> see screenshot

**Expected behavior**
I want to be able to use the mobile app with a custom certificate and https on my mobile phone.

**Logs**

**Screenshots**
App:
![Screenshot_20210418-094909](https://user-images.githubusercontent.com/34819524/115138310-a0fe7280-a02b-11eb-9892-23d2378fd92d.png)
Browser:
![Screenshot_20210418-094956](https://user-images.githubusercontent.com/34819524/115138311-a22f9f80-a02b-11eb-8de0-42956ab5acfd.png)
My certificate:
![image](https://user-images.githubusercontent.com/34819524/115138585-68f82f00-a02d-11eb-90ed-f88883c4e957.png)

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 9
 - Device manufacturer and model: LG G7 fit
 - Jellyfin server version: 10.7.2
 - I am to able to reach this point: The type of video player implementation used: [web player or integrated player (ExoPlayer)]

**Additional context**
On the browser I am only able to use https with the hostname (pc hostnames, phone ignore the wrong certificate) correctly: 
![image](https://user-images.githubusercontent.com/34819524/115138618-8af1b180-a02d-11eb-9224-435c4bb7959f.png)

On my phone I am not able to use the dns server of my router. -> I don't have hostnames (dns names).

Maybe you could add a option enable a fix with IP Adresses and Certificates? (But in the app hostnames are also not working)
